Fix comment and add error checking to session-to-html-in-home

diff --git a/session-to-html-in-home b/session-to-html-in-home
--- a/session-to-html-in-home
+++ b/session-to-html-in-home
@@ -1,6 +1,13 @@
 #!/usr/bin/env zsh
 # Convert a Firefox .session file to an HTML file
-# Usage: session-to-html foo.session > foo.html
+# Usage: session-to-html foo.session
+# Automatically makes ~/foo.html
 n=${@%.*}
 d=~/$n.html
+
+if [[ -e $d ]]; then
+    echo "$0: error: $d exists"
+    exit 1
+fi
+
 session-to-tsv < "$@" | awk -v n="$n" -F'\t' 'function escapeName(name) { gsub(/&/, "\\&amp;", name); gsub(/</, "\\&lt;", name); gsub(/>/, "\\&gt;", name); return name; } function escapeUrl(url) { url = escapeName(url); gsub(/"/, "\\&#39;", url); return url; } BEGIN { print "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>"escapeName(n)"</title></head><body><ul>" } /\w+/ { url = escapeUrl($2); if (length($1) > 0) { name = escapeName($1) } else { name = url } print "<li><a href=\""url"\">"name"</a></li>" } END { print "</ul></body></html>" }' > $d
